version: "3.8"
services:
  frontend:
    build:
      context: ./frontend # path to frontend project
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - appnet
    # no ports published for frontend; main nginx will proxy request to it
    depends_on:
      - auth-service
      - courses-service
      - recommender-service

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - appnet

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    networks:
      - appnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - appnet
    volumes:
      - esdata:/usr/share/elasticsearch/data

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    env_file: .env
    ports:
      - "3001:3001"
    depends_on: [mongo]
    networks:
      - appnet

  courses-service:
    build: ./backend/courses-service
    container_name: courses-service
    env_file: .env
    ports:
      - "3003:3003"
    depends_on: [mongo, redis, elasticsearch, auth-service]
    networks:
      - appnet

  recommender-service:
    build: ./backend/recommender-service
    container_name: recommender-service
    env_file: .env
    ports:
      - "3002:3002"
    depends_on: [auth-service]
    networks:
      - appnet

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - courses-service
      - recommender-service
      - frontend
    networks:
      - appnet

volumes:
  mongo-data:
  esdata:

networks:
  appnet:
    driver: bridge
